apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: NodePort  # Cambiado a NodePort
  ports:
    - port: 30000         # Puerto del servicio
      targetPort: 8080    # Puerto del contenedor
      nodePort: 30000     # puerto host.
  selector:
    app: jenkins
