apiVersion: v1
kind: Namespace
metadata:
  name: juan-namespace

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: juan-namespace
type: Opaque
data:
  mysql-root-password: cm9vdC1wYXNz # "root-pass" codificado en Base64
  mysql-user: anVhbg==               # "juan" codificado en Base64
  mysql-password: bXlzcWxwYXNz       # "mysql-pass" codificado en Base64 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-a
  namespace: juan-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-b
  namespace: juan-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: juan-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80



# ===========<---- MYSQL INSTANCIAS ---->===========#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment-a
  namespace: juan-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: mysql-root-password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: mysql-password
          volumeMounts:
            - name: mysql-storage-a
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage-a
          persistentVolumeClaim:
            claimName: mysql-pvc-a

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment-b
  namespace: juan-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: mysql-root-password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: mysql-password
          volumeMounts:
            - name: mysql-storage-b
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage-b
          persistentVolumeClaim:
            claimName: mysql-pvc-b